using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using SistemPengurusanKehadiran.Models;using SistemPengurusanKehadiran.Services;
namespace SistemPengurusanKehadiran.Pages;
public sealed partial class InterventionsPage:Page
{
    private InterventionRecord current=new();private List<Student> students=[];private List<Teacher> teachers=[];
    public InterventionsPage(){InitializeComponent();Loaded+=(_,_)=>{students=DatabaseService.Instance.GetStudents();teachers=DatabaseService.Instance.GetTeachers().Where(x=>x.Aktif).ToList();StudentPicker.ItemsSource=students;TeacherPicker.ItemsSource=teachers;InterventionType.ItemsSource=new[]{"KEHADIRAN","KAUNSELING","KEBAJIKAN","KELUARGA","AKADEMIK","LAIN-LAIN"};Status.ItemsSource=new[]{"DIRANCANG","DALAM TINDAKAN","SELESAI","TIDAK BERJAYA"};NewRecord();Refresh();};}
    private void Refresh(){var x=DatabaseService.Instance.GetInterventions(Search?.Text??"");List.ItemsSource=x;CountText.Text=$"{x.Count} INTERVENSI";}
    private void NewRecord(){current=new InterventionRecord{InterventionDate=DateTime.Today,InterventionType="KEHADIRAN",Status="DIRANCANG"};StudentPicker.SelectedItem=null;TeacherPicker.SelectedItem=null;InterventionDate.Date=DateTimeOffset.Now;InterventionType.SelectedItem="KEHADIRAN";Status.SelectedItem="DIRANCANG";HasTarget.IsChecked=false;TargetDate.IsEnabled=false;TargetDate.Date=DateTimeOffset.Now;Action.Text=Result.Text=Notes.Text="";List.SelectedItem=null;FormTitle.Text="Intervensi Baharu";FormStatus.Text="Rekod baharu.";}
    private void HasTarget_Changed(object sender,RoutedEventArgs e)=>TargetDate.IsEnabled=HasTarget.IsChecked==true;
    private void New_Click(object sender,RoutedEventArgs e)=>NewRecord();
    private void Save_Click(object sender,RoutedEventArgs e){if(StudentPicker.SelectedItem is not Student s){FormStatus.Text="Pilih murid terlebih dahulu.";return;}if(string.IsNullOrWhiteSpace(Action.Text)){FormStatus.Text="Tindakan / strategi intervensi mesti diisi.";return;}current.StudentId=s.Id;current.InterventionDate=InterventionDate.Date.DateTime;current.InterventionType=InterventionType.SelectedItem?.ToString()??"KEHADIRAN";current.TeacherId=(TeacherPicker.SelectedItem as Teacher)?.Id??"";current.TargetDate=HasTarget.IsChecked==true?TargetDate.Date.DateTime:null;current.Status=Status.SelectedItem?.ToString()??"DIRANCANG";current.Action=Action.Text;current.Result=Result.Text;current.Notes=Notes.Text;DatabaseService.Instance.SaveIntervention(current);FormStatus.Text="Intervensi berjaya disimpan.";Refresh();}
    private void Delete_Click(object sender,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(current.Id))return;DatabaseService.Instance.DeleteIntervention(current.Id);NewRecord();FormStatus.Text="Rekod dipadam (soft delete).";Refresh();}
    private void Search_TextChanged(object sender,TextChangedEventArgs e)=>Refresh();
    private void List_SelectionChanged(object sender,SelectionChangedEventArgs e){if(List.SelectedItem is not InterventionRecord x)return;current=x;StudentPicker.SelectedItem=students.FirstOrDefault(s=>s.Id==x.StudentId);TeacherPicker.SelectedItem=teachers.FirstOrDefault(t=>t.Id==x.TeacherId);InterventionDate.Date=new DateTimeOffset(x.InterventionDate);InterventionType.SelectedItem=x.InterventionType;Status.SelectedItem=x.Status;HasTarget.IsChecked=x.TargetDate is not null;TargetDate.IsEnabled=x.TargetDate is not null;TargetDate.Date=new DateTimeOffset(x.TargetDate??DateTime.Today);Action.Text=x.Action;Result.Text=x.Result;Notes.Text=x.Notes;FormTitle.Text="Maklumat Intervensi";FormStatus.Text="Mod kemas kini.";}
}
